# coding: utf-8

# flake8: noqa
"""
    Bel VEB exchange rates

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from belveb_exchange_client.models.rate import Rate
