"""
    Bel VEB exchange rates

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import belveb_exchange_client
from belveb_exchange_client.model.rate import Rate
globals()['Rate'] = Rate
from belveb_exchange_client.model.rates import Rates


class TestRates(unittest.TestCase):
    """Rates unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRates(self):
        """Test Rates"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Rates()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
