"""
    Bel VEB exchange rates

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import belveb_exchange_client
from belveb_exchange_client.model.decimal import Decimal
globals()['Decimal'] = Decimal
from belveb_exchange_client.model.rate import Rate


class TestRate(unittest.TestCase):
    """Rate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRate(self):
        """Test Rate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Rate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
