# flake8: noqa

"""
    Bel VEB exchange rates

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from belveb_exchange_client.api_client import ApiClient

# import Configuration
from belveb_exchange_client.configuration import Configuration

# import exceptions
from belveb_exchange_client.exceptions import OpenApiException
from belveb_exchange_client.exceptions import ApiAttributeError
from belveb_exchange_client.exceptions import ApiTypeError
from belveb_exchange_client.exceptions import ApiValueError
from belveb_exchange_client.exceptions import ApiKeyError
from belveb_exchange_client.exceptions import ApiException
